[[constraint]]
  branch = "master"
  name = "github.com/davidkhala/goutils"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "release-1.4"
# TODO jira issue https://jira.hyperledger.org/browse/FAB-10936

#FIXME if test passed, please clean up this 'fsouza/go-dockerclient' section
[[override]]
    name = "github.com/fsouza/go-dockerclient"
    version = "=1.2.1"
[prune]
  go-tests = true
  unused-packages = true
