[[constraint]]
  branch = "master"
  name = "github.com/davidkhala/goutils"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "master"
# TODO problem in vendor/github.com/docker/docker/opts/address_pools.go:15:12: undefined: ipamutils.NetworkToSplit
# TODO jira issue https://jira.hyperledger.org/browse/FAB-10936
# TODO dep issue: https://github.com/golang/dep/issues/1888

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"

[prune]
  go-tests = true
  unused-packages = true
