[[constraint]]
  branch = "master"
  name = "github.com/davidkhala/goutils"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "master"
# TODO jira issue https://jira.hyperledger.org/browse/FAB-10936

[[override]]
    name = "github.com/fsouza/go-dockerclient"
    version = "=1.2.1"

[prune]
  go-tests = true
  unused-packages = true
