name: Go

on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: 1.18
    - run: go mod vendor
      name: vendor
    - name: Test
      run: go test -v ./...
