name: Go

on:
  push:
    branches: [ master ]


jobs:
  root:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: "1.20"
    - run: go mod vendor
      name: vendor
    - name: Test
      run: go test -v ./...
  contract-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract-api
    steps:
      - uses: actions/checkout@main
      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "1.20"
      - run: go mod vendor
        name: vendor
      - name: Test
        run: go test -v ./...