name: Go

on: [ push,workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: vendor
        run: go mod vendor

      - name: Test
        run: go test -v ./...
